# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\软件实训\Custom_Layer_Widget_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 77)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Layer_widget_button_layout_1 = QtWidgets.QVBoxLayout()
        self.Layer_widget_button_layout_1.setObjectName("Layer_widget_button_layout_1")
        self.Layer_widget_visible_button1 = QtWidgets.QPushButton(Form)
        self.Layer_widget_visible_button1.setMinimumSize(QtCore.QSize(20, 20))
        self.Layer_widget_visible_button1.setMaximumSize(QtCore.QSize(20, 20))
        self.Layer_widget_visible_button1.setObjectName("Layer_widget_visible_button1")
        self.Layer_widget_button_layout_1.addWidget(self.Layer_widget_visible_button1)
        self.Layer_widget_lock_button1 = QtWidgets.QPushButton(Form)
        self.Layer_widget_lock_button1.setMinimumSize(QtCore.QSize(20, 20))
        self.Layer_widget_lock_button1.setMaximumSize(QtCore.QSize(20, 20))
        self.Layer_widget_lock_button1.setObjectName("Layer_widget_lock_button1")
        self.Layer_widget_button_layout_1.addWidget(self.Layer_widget_lock_button1)
        self.horizontalLayout.addLayout(self.Layer_widget_button_layout_1)
        self.Layer_widget_preview_label_1 = QtWidgets.QLabel(Form)
        self.Layer_widget_preview_label_1.setObjectName("Layer_widget_preview_label_1")
        self.horizontalLayout.addWidget(self.Layer_widget_preview_label_1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.Layer_widget_layer_name_1 = QtWidgets.QLabel(Form)
        self.Layer_widget_layer_name_1.setObjectName("Layer_widget_layer_name_1")
        self.verticalLayout_24.addWidget(self.Layer_widget_layer_name_1)
        self.Layer_widget_layer_mod_1 = QtWidgets.QLabel(Form)
        self.Layer_widget_layer_mod_1.setObjectName("Layer_widget_layer_mod_1")
        self.verticalLayout_24.addWidget(self.Layer_widget_layer_mod_1)
        self.Layer_widget_layer_Opacity_1 = QtWidgets.QLabel(Form)
        self.Layer_widget_layer_Opacity_1.setObjectName("Layer_widget_layer_Opacity_1")
        self.verticalLayout_24.addWidget(self.Layer_widget_layer_Opacity_1)
        self.horizontalLayout.addLayout(self.verticalLayout_24)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Layer_widget_visible_button1.setText(_translate("Form", "见"))
        self.Layer_widget_lock_button1.setText(_translate("Form", "锁"))
        self.Layer_widget_preview_label_1.setText(_translate("Form", "预览"))
        self.Layer_widget_layer_name_1.setText(_translate("Form", "名"))
        self.Layer_widget_layer_mod_1.setText(_translate("Form", "模式"))
        self.Layer_widget_layer_Opacity_1.setText(_translate("Form", "不透明度"))
