# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\软件实训\Custom_Widgets\Layer_Widget_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Layer_Widget_UI(object):
    def setupUi(self, Layer_Widget_UI):
        Layer_Widget_UI.setObjectName("Layer_Widget_UI")
        Layer_Widget_UI.resize(400, 78)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Layer_Widget_UI)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Visible_button = QtWidgets.QPushButton(Layer_Widget_UI)
        self.Visible_button.setMinimumSize(QtCore.QSize(20, 20))
        self.Visible_button.setMaximumSize(QtCore.QSize(20, 20))
        self.Visible_button.setObjectName("Visible_button")
        self.verticalLayout_2.addWidget(self.Visible_button)
        self.Lock_button = QtWidgets.QPushButton(Layer_Widget_UI)
        self.Lock_button.setMinimumSize(QtCore.QSize(20, 20))
        self.Lock_button.setMaximumSize(QtCore.QSize(20, 20))
        self.Lock_button.setObjectName("Lock_button")
        self.verticalLayout_2.addWidget(self.Lock_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.Preview_label = QtWidgets.QLabel(Layer_Widget_UI)
        self.Preview_label.setMinimumSize(QtCore.QSize(60, 60))
        self.Preview_label.setMaximumSize(QtCore.QSize(60, 60))
        self.Preview_label.setObjectName("Preview_label")
        self.horizontalLayout.addWidget(self.Preview_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Layer_name_label = QtWidgets.QLabel(Layer_Widget_UI)
        self.Layer_name_label.setObjectName("Layer_name_label")
        self.verticalLayout.addWidget(self.Layer_name_label)
        self.Layer_mod_label = QtWidgets.QLabel(Layer_Widget_UI)
        self.Layer_mod_label.setObjectName("Layer_mod_label")
        self.verticalLayout.addWidget(self.Layer_mod_label)
        self.Layer_opacity_label = QtWidgets.QLabel(Layer_Widget_UI)
        self.Layer_opacity_label.setObjectName("Layer_opacity_label")
        self.verticalLayout.addWidget(self.Layer_opacity_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi(Layer_Widget_UI)
        QtCore.QMetaObject.connectSlotsByName(Layer_Widget_UI)

    def retranslateUi(self, Layer_Widget_UI):
        _translate = QtCore.QCoreApplication.translate
        self.Visible_button.setText(_translate("Layer_Widget_UI", "见"))
        self.Lock_button.setText(_translate("Layer_Widget_UI", "锁"))
        self.Preview_label.setText(_translate("Layer_Widget_UI", "预览"))
        self.Layer_name_label.setText(_translate("Layer_Widget_UI", "名"))
        self.Layer_mod_label.setText(_translate("Layer_Widget_UI", "模式"))
        self.Layer_opacity_label.setText(_translate("Layer_Widget_UI", "不透明度"))
